# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default=None, max_length=30)),
                ('category', models.CharField(default=None, max_length=20)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
